pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                // Compile and run Java code
                bat 'javac -sourcepath src -d out IdeaProjects/TestngProject/src/Annotation/Annotation1.java'
                bat 'java -cp out Annotation1'
            }
        }
    }
}
